[project]
name = "geoacled"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopandas>=1.1.1",
    "httpx>=0.28.1",
    "polars>=1.35.1",
    "pycountry>=24.6.1",
    "python-dotenv>=1.2.1",
]
